### ISSUE TITLE
Random lockups

### ISSUE THREAD

**Issue by TMW2N** [kevinabrandon/AboveTustin#13]
the bot, running on latest raspbian lite randomly locks up for me.  errors in the console output when it locks up are below

Now: 2017-05-24 12:24:08.700000+00:00
Traceback (most recent call last):
  File "tracker.py", line 121, in <module>
    fd.refresh()
  File "/home/pi/AboveTustin/flightdata.py", line 57, in refresh
    self.raw_data = self.req.read()
  File "/usr/lib/python3.4/http/client.py", line 512, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.4/http/client.py", line 664, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(17576 bytes read, 151 more expected)

**Comment by kevinabrandon** [comment]
This has been bothering me for months now... I think it's finally fixed.  I've been running the fix for a few days now without a single crash.
